"""MCP server exposing Calculate-PBN augmented deal data.

Transport: streamable HTTP (endpoint /mcp) on PBN_POSTMORTEM_MCP_PORT
(default 8513), stateless with JSON responses so plain HTTP clients and
cloudflared work without session affinity. Same pattern as
Bridge_Game_Postmortem_Chatbot/acbl_postmortem_mcp_server.py.

Data source: the parquet cache written by the Streamlit app
(calculate_pbn_results_streamlit.py saves each augmented dataframe to
cache/df-{key}.parquet, key derived from the source PBN URL). This server is
a read-only SQL/report layer over that cache via pbn_postmortem_service; it
never downloads PBNs or re-runs augmentation. Caches are generated by loading
https://pbn.postmortem.chat/?url=<PBN url>.

Deployment: calculate-pbn-mcp container, started by
../7nt/postmortem_start.ps1. GET /health is used by the wslc watchdog and
deploy health checks.
"""

import os
from typing import Any, Dict, Optional

from mcp.server.mcpserver import MCPServer
from starlette.requests import Request
from starlette.responses import JSONResponse

import pbn_postmortem_service as svc

PBN_POSTMORTEM_MCP_PORT = int(os.environ.get("PBN_POSTMORTEM_MCP_PORT", "8513"))

mcp = MCPServer("pbn-postmortem")


@mcp.custom_route("/health", methods=["GET"])
async def health(request: Request) -> JSONResponse:
    """Liveness probe for the wslc watchdog / deploy health check."""
    info = svc.dataset_info()
    return JSONResponse(
        {
            "status": "ok",
            "service": "calculate-pbn-mcp",
            "cache_dir": info["cache_dir"],
            "cached_postmortems": info["cached_postmortems"],
        }
    )


@mcp.tool()
def pbn_postmortem_dataset_info() -> Dict[str, Any]:
    """Summary of the Calculate-PBN cache: how many augmented PBN dataframes
    are cached, their keys, and how new ones get generated."""
    return svc.dataset_info()


@mcp.tool()
def pbn_postmortem_games(limit: int = 100) -> Dict[str, Any]:
    """List cached Calculate-PBN games (newest first). Each entry has the
    cache key, the source PBN URL, and cache timestamps. A game must appear
    here before the boards/sql/schema tools can query it."""
    games = svc.list_cached_postmortems()[: max(1, min(limit, 500))]
    return {"games": games, "count": len(games)}


@mcp.tool()
def pbn_postmortem_boards(
    key: Optional[str] = None,
    columns: Optional[str] = None,
    limit: int = 100,
) -> Dict[str, Any]:
    """Per-board results for one cached Calculate-PBN game: contract,
    declarer, result, tricks, scores, matchpoint percentages, and the deal
    (PBN).

    key: cache key or source PBN URL from pbn_postmortem_games; omit for the
    most recently cached game.
    columns: optional comma-separated column names to override the default
    summary set (discover names with pbn_postmortem_schema).
    """
    df, meta = svc.load_postmortem(key)
    cols = [c.strip() for c in columns.split(",")] if columns else None
    return svc.board_results(df, meta, columns=cols, limit=limit)


@mcp.tool()
def pbn_postmortem_sql(
    sql: str,
    key: Optional[str] = None,
    limit: int = svc.DEFAULT_SQL_ROW_LIMIT,
) -> Dict[str, Any]:
    """Run a DuckDB SQL query against one cached Calculate-PBN game,
    registered as table 'self' (one row per board result, thousands of
    augmented columns: double-dummy, par, single-dummy expected values, HCP,
    ...).

    'FROM self' is prepended when the query does not reference it, so both
    'SELECT ... FROM self ...' and DuckDB's 'SELECT ...' shorthand work.
    Unlike the ACBL/ffbridge postmortem MCPs there is no player
    personalization: PBN files rarely carry player ids, so helper columns
    like Boards_I_Played exist but are all true unless the source had ids.
    key: cache key or source PBN URL; omit for the most recently cached game.
    """
    df, meta = svc.load_postmortem(key)
    result = svc.run_sql(df, sql, limit=limit)
    result["meta"] = meta
    return result


@mcp.tool()
def pbn_postmortem_schema(
    key: Optional[str] = None,
    pattern: Optional[str] = None,
    limit: int = 200,
) -> Dict[str, Any]:
    """Column names and dtypes of one cached Calculate-PBN dataframe. The
    frame has thousands of augmented columns, so pass a case-insensitive
    regex pattern (e.g. 'Pct|Score', '^DD_', 'Par') to search for relevant
    ones before writing pbn_postmortem_sql queries."""
    df, _ = svc.load_postmortem(key)
    return svc.schema_columns(df, pattern=pattern, limit=limit)


if __name__ == "__main__":
    print(
        f"[calculate-pbn-mcp] starting on :{PBN_POSTMORTEM_MCP_PORT} "
        f"(endpoint /mcp, health /health); cache -> {svc.CACHE_DIR}",
        flush=True,
    )
    # Stateless + JSON responses: plain request/response tools, no session
    # affinity needed behind cloudflared, and curl-testable.
    mcp.run(
        transport="streamable-http",
        host="0.0.0.0",
        port=PBN_POSTMORTEM_MCP_PORT,
        stateless_http=True,
        json_response=True,
    )
